# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=60)),
                ('resume_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
