# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('resume_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
