# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-03-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME_APP', '0002_auto_20220324_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('rank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='')),
                ('resume_score', models.FloatField()),
            ],
        ),
    ]
